# PowerShell — PythonMulakat .env Setup Script
# Backend klasörüne .env oluşturur, tüm secrets'ı toplar

param(
    [string]$BackendDir = "C:\projelerim\gozbegim\backend"
)

Write-Host ""
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  PythonMulakat Backend .env Setup" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Backend klasörü var mı
if (-not (Test-Path $BackendDir)) {
    Write-Host "❌ Backend klasörü yok: $BackendDir" -ForegroundColor Red
    Write-Host "   Doğru yolu göstermek için:" -ForegroundColor Yellow
    Write-Host "   .\setup-env.ps1 -BackendDir 'C:\projelerim\gozbebgim\backend'" -ForegroundColor White
    exit 1
}

$envPath = Join-Path $BackendDir ".env"

# Mevcut .env kontrol
if (Test-Path $envPath) {
    Write-Host "⚠️  Mevcut .env dosyası var: $envPath" -ForegroundColor Yellow
    $backup = "$envPath.bak.$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item $envPath $backup -Force
    Write-Host "💾 Yedek: $backup" -ForegroundColor Green
    Write-Host ""
}

Write-Host "📝 Değerleri topluyorum..." -ForegroundColor Yellow
Write-Host ""

# 1. Supabase URL
Write-Host "1️⃣  SUPABASE_URL" -ForegroundColor Cyan
Write-Host "    Supabase Dashboard → Settings → API → Project URL" -ForegroundColor Gray
$supabaseUrl = Read-Host "    URL (örn: https://abc123.supabase.co)"
if ([string]::IsNullOrWhiteSpace($supabaseUrl)) {
    Write-Host "❌ URL zorunlu!" -ForegroundColor Red
    exit 1
}

# 2. Supabase Anon Key
Write-Host ""
Write-Host "2️⃣  SUPABASE_ANON_KEY" -ForegroundColor Cyan
Write-Host "    Supabase Dashboard → Settings → API → anon / public key" -ForegroundColor Gray
Write-Host "    eyJ... ile başlar (güvenli public key)" -ForegroundColor Gray
$anonKey = Read-Host "    Key"

# 3. Supabase Service Role Key
Write-Host ""
Write-Host "3️⃣  SUPABASE_SERVICE_ROLE_KEY" -ForegroundColor Cyan
Write-Host "    Supabase Dashboard → Settings → API → service_role key" -ForegroundColor Gray
Write-Host "    ⚠️  GİZLİ — Backend'e özel, ASLA frontend'de kullanma!" -ForegroundColor Red
Write-Host "    eyJ... ile başlar (bypass RLS)" -ForegroundColor Gray
$serviceKey = Read-Host "    Key"

# 4. Resend API Key
Write-Host ""
Write-Host "4️⃣  RESEND_API_KEY" -ForegroundColor Cyan
Write-Host "    https://resend.com/signup → Dashboard → API Keys" -ForegroundColor Gray
Write-Host "    Permission: Full access" -ForegroundColor Gray
$resendKey = Read-Host "    Key (re_xxxx)"

# 5. Resend From Email
Write-Host ""
Write-Host "5️⃣  RESEND_FROM_EMAIL" -ForegroundColor Cyan
Write-Host "    Test mode: onboarding@resend.dev (ENTER)" -ForegroundColor Gray
Write-Host "    Production: noreply@pythonmulakat.com (domain doğrulama gerekli)" -ForegroundColor Gray
$fromEmail = Read-Host "    Email (ENTER = test mode)"
if ([string]::IsNullOrWhiteSpace($fromEmail)) {
    $fromEmail = "onboarding@resend.dev"
}

# 6. Frontend ENV dosyaları
Write-Host ""
Write-Host "6️⃣  Frontend .env.local (opsiyonel)" -ForegroundColor Cyan
$frontendDir = "C:\projelerim\gozbegim\frontend"
if (Test-Path $frontendDir) {
    $createFrontend = Read-Host "    Frontend .env.local da oluştur? (E/h)"
    if ($createFrontend -in @("", "E", "e", "Y", "y")) {
        $frontEnvPath = Join-Path $frontendDir ".env.local"
        $nextAnonKey = $anonKey  # Frontend için aynı anon key
        Set-Content -Path $frontEnvPath -Value @"
NEXT_PUBLIC_SUPABASE_URL=$supabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$nextAnonKey
NEXT_PUBLIC_API_URL=http://localhost:8000
"@
        Write-Host "    ✅ Frontend .env.local oluşturuldu" -ForegroundColor Green
    }
}

# ─── .env yaz ─────────────────────────────────────────
$envContent = @"
# ═══════════════════════════════════════════════════════════════
# PythonMulakat Backend — Environment Variables
# Auto-generated by setup-env.ps1
# ⚠️  ASLA commit etme! .gitignore'da olmalı.
# ═══════════════════════════════════════════════════════════════

# ─── Supabase ───────────────────────────────────────────
SUPABASE_URL=$supabaseUrl
SUPABASE_ANON_KEY=$anonKey
SUPABASE_SERVICE_ROLE_KEY=$serviceKey
SUPABASE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder

# ─── Email (Resend) ───────────────────────────────────
RESEND_API_KEY=$resendKey
RESEND_FROM_EMAIL=$fromEmail

# ─── CORS ──────────────────────────────────────────────
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,https://www.pythonmulakat.com

# ─── App ───────────────────────────────────────────────
APP_VERSION=2.4
DEBUG=True
LOG_LEVEL=INFO
"@

Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ✅ .env başarıyla oluşturuldu!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "📁 Dosya: $envPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "İçerik:" -ForegroundColor Yellow
Get-Content $envPath | ForEach-Object { Write-Host "   $_" -ForegroundColor Gray }
Write-Host ""

# Test
Write-Host "🧪 Test ediyorum..." -ForegroundColor Yellow
Set-Location $BackendDir

# Backend restart öner
Write-Host ""
Write-Host "Backend'i restart et:" -ForegroundColor Cyan
Write-Host "   cd $BackendDir" -ForegroundColor White
Write-Host "   uvicorn main:app --reload --port 8000" -ForegroundColor White
Write-Host ""
Write-Host "📧 Email testi için register ol. Backend log'da:" -ForegroundColor Cyan
Write-Host "   📧 [RESEND] OK → test@gmail.com (id: abc123)" -ForegroundColor Gray
Write-Host ""
